[package]
name = "rust_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.37"
log = "0.4.21"
simplelog = "0.12.2"
windows = "0.58.0"
sdl2 = "0.37.0"

[build-dependencies]
cbindgen = "0.27.0"