pub enum Layer {
    Execute,
    Realize,
    SeaExecute,
    SeaRealize,
    InterfaceExecute,
    InterfaceRealize,
    FaderExecute,
    FaderRealize,
    LighterExecute,
    LighterRealize,
    VideoExecute,
    VideoRealize,
    EditorRealize,
    InfoRealize,
    SoundDebugRealize,
    SeaReflection,
    SeaReflection2,
    SeaSunRoad,
    SunTrace,
    SailsTrace,
    HullTrace,
    MastIslandTrace,
    MastShipTrace,
    ShipCannonTrace,
    FortCannonTrace,
    IslandTrace,
    Shadow,
    Blood,
    RainDrops,
    TwentyNine,
    Thirty,
    ThirtyOne,
    Invalid
}

impl Layer {
    pub fn by_index(index: u32) -> Layer {
        match index {
            0 => Layer::Execute,
            1 => Layer::Realize,
            2 => Layer::SeaExecute,
            3 => Layer::SeaRealize,
            4 => Layer::InterfaceExecute,
            5 => Layer::InterfaceRealize,
            6 => Layer::FaderExecute,
            7 => Layer::FaderRealize,
            8 => Layer::LighterExecute,
            9 => Layer::LighterRealize,
            10 => Layer::VideoExecute,
            11 => Layer::VideoRealize,
            12 => Layer::EditorRealize,
            13 => Layer::InfoRealize,
            14 => Layer::SoundDebugRealize,
            15 => Layer::SeaReflection,
            16 => Layer::SeaReflection2,
            17 => Layer::SeaSunRoad,
            18 => Layer::SunTrace,
            19 => Layer::SailsTrace,
            20 => Layer::HullTrace,
            21 => Layer::MastIslandTrace,
            22 => Layer::MastShipTrace,
            23 => Layer::ShipCannonTrace,
            24 => Layer::FortCannonTrace,
            25 => Layer::IslandTrace,
            26 => Layer::Shadow,
            27 => Layer::Blood,
            28 => Layer::RainDrops,
            29 => Layer::TwentyNine,
            30 => Layer::Thirty,
            31 => Layer::ThirtyOne,
            _ => Layer::Invalid
        }
    }
}
